### ISSUE TITLE
Monitor multiple boxes threads issue

### ISSUE THREAD

**Issue by Sylar-A** [danzuep/MailKitSimplified#63]
Hi, @danzuep!

At first, thanks a lot for the monitoring multiple boxes feature!
At second, there is some issue with it.
I have registered 7 FolderMonitors in appsettings and using IMailFolderMonitorFactory.MonitorAllMailboxesAsync method to monitor them. So, for example (and not only this example), when i get 2 mail in 1 mailbox same time, it's thows exceptions:
```
MailKitSimplified.Receiver.Services.MailFolderMonitor|IMAP client is being accessed by multiple threads. System.InvalidOperationException: The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.
   at MailKit.Net.Imap.ImapEngine.PopNextCommand()
   at MailKit.Net.Imap.ImapEngine.IterateAsync()
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic)
   at MailKit.Net.Imap.ImapClient.NoOpAsync(CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderMonitor.ProcessMessagesArrivedAsync(Boolean firstConnection, CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderMonitor.WaitForNewMessagesAsync(CancellationToken cancellationToken)
```
```
MailKitSimplified.Receiver.Services.MailFolderMonitor|Error occurred processing arrival queue item #MailKit.MessageSummary. System.InvalidOperationException: The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.
   at MailKit.Net.Imap.ImapEngine.PopNextCommand()
   at MailKit.Net.Imap.ImapEngine.IterateAsync()
   at MailKit.Net.Imap.ImapEngine.RunAsync(ImapCommand ic)
   at MailKit.Net.Imap.ImapFolder.GetBodyPartAsync(UniqueId uid, String partSpecifier, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKitSimplified.Receiver.Extensions.MessageSummaryExtensions.GetBodyTextAsync(IMessageSummary messageSummary, CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderMonitor.ProcessArrivalQueueAsync(Func`2 messageArrivalMethod, CancellationToken cancellationToken)
```
At third, there is example with [worker](https://github.com/danzuep/MailKitSimplified/blob/main/samples/WorkerServiceExample/Worker.cs#L15) which is [Singleton](https://learn.microsoft.com/en-us/dotnet/core/extensions/scoped-service) and have injected from constructor dependency on [IImapReceiver](https://github.com/danzuep/MailKitSimplified/blob/main/samples/WorkerServiceExample/Worker.cs#L19), which is [Transient](https://github.com/danzuep/MailKitSimplified/blob/main/source/MailKitSimplified.Receiver/Extensions/ServiceCollectionExtensions.cs#L72). So, it won't be transient, WorkerService will control it's lifetime, and it would be Singleton. There is [recomendation](https://learn.microsoft.com/en-us/dotnet/core/extensions/scoped-service) from Microcoft to do it rigth way.

Exceptions throws every day several times😥
Please, help, Daniel🙏

**Comment by danzuep** [comment]
Hi @Sylar-A, glad you found the FolderMonitor feature as I'm not sure I'd documented it fully 😊. I ran it in my test environment but the project I initially wanted to use it for has been and gone, so I haven't actually used it in a real-world setting yet. It sounds like you've figured out the fix for this issue though, so well done! Please make a fork of the project, test your proposed changes on your machine, then make a pull request to merge your changes into the main branch. Then your name will appear on the main page as a contributor 🙂

**Comment by Sylar-A** [comment]
Hi, @danzuep!
I have found a fix for another issue in sample code, but it's not fix my issue with multiple threads😞

**Comment by danzuep** [comment]
As a short-term workaround you could try using the ImapReceiverFactory instead. If that works then using the [copy](https://github.com/danzuep/MailKitSimplified/blob/f0a191510082e86d3b39e6b53d3f74b4eb998401/source/MailKitSimplified.Receiver/Services/ImapReceiverFactory.cs#L38) function could be the solution.

**Comment by Sylar-A** [comment]
Hi, @danzuep!

If i understand you correct, it must be a BackgroundService with while loop and with some timeout?
For example:
```
    private async Task DoWork(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            await Task.Delay(TimeSpan.FromMinutes(1), cancellationToken);

            using var scope = _serviceProvider.CreateScope();

            var imapReceiverFactory = scope.ServiceProvider
                .GetRequiredService<IImapReceiverFactory>();

            foreach (var receiver in imapReceiverFactory.GetAllImapReceivers())
            {
                var messageSummaries = await receiver.ReadMail.GetMessageSummariesAsync(cancellationToken);

                foreach (var messageSummary in messageSummaries)
                {
                    // Do something...
                }
            }
        }
    }
```
But i didn't realize how to use the copy method as you suggested.

**Comment by Sylar-A** [comment]
Oh, ok, Daniel, thanks for parting words, i'll try to hard debug it😅

**Comment by danzuep** [comment]
Looking back at the error message, it says the "IMAP client is being accessed by multiple threads." The IMAP client isn't being passed through when the [MailFolderMonitor](https://github.com/danzuep/MailKitSimplified/blob/f0a191510082e86d3b39e6b53d3f74b4eb998401/source/MailKitSimplified.Receiver/Services/MailFolderMonitor.cs#L71) is [constructed](https://github.com/danzuep/MailKitSimplified/blob/f0a191510082e86d3b39e6b53d3f74b4eb998401/source/MailKitSimplified.Receiver/Services/ImapReceiver.cs#L89) though. Then I saw the second part that says "GetBodyTextAsync(IMessageSummary)". The short term fix then is not to use `messageSummary.Folder`. Hopefully that helps to with a more targeted search 🙂

**Comment by Sylar-A** [comment]
Hi, @danzuep!

I have found another issue with IImapReceiverFactory. When it's creates new receivers and all of them have same ImapHost, it's takes only one mail (in my case one same mail seven times instead of 7 different mails). When I debugging it, the problem was in IMemoryCache extension method GetOrCreate (from Microsoft). Because of all mails have same ImapHost, it wasn't creates new item and tooks the same item 7 times by the key. It was [here](https://github.com/danzuep/MailKitSimplified/blob/main/source/MailKitSimplified.Receiver/Services/ImapReceiverFactory.cs#L64).

**Comment by danzuep** [comment]
Wow, good find! `_memoryCache` can be removed, it doesn't add much in terms of functionality or speed. Are you happy to add it to a pull request? If so, please submit each fix as a separate pull request if possible, but all good if not.

**Comment by Sylar-A** [comment]
Ok, Daniel. I could do it later.

**Comment by danzuep** [comment]
Hey @Sylar-A, is the issue you found fixed?

You also mentioned changing to scoped services, but I don't see those in the fork on your profile. I've done that for the [Sender](https://github.com/danzuep/MailKitSimplified/blob/e4218e55cb51de7b0da720f1bbd07271a738b488/source/MailKitSimplified.Sender/Extensions/ServiceCollectionExtensions.cs#L72), but I guess I never got around to it for the Receiver so I should get on to it.

**Comment by danzuep** [comment]
The answer to this issue you've found is to not use use the messageSummary that comes from the MailFolderMonitor or the messageSummary.Folder. I've added a MailFolderCache function you can use from the ImapReceiver, so use the UniqueId and the GetMailFolderAsync() function instead of using the MessageSummary directly. One possible solution would be for me to just return the UniqueId instead of returning the MessageSummary.

**Comment by danzuep** [comment]
Here's a sample: 
```ps
        using var scope = _serviceScopeFactory.CreateScope();
        var mailFolderClient = scope.ServiceProvider.GetRequiredService<IMailFolderClient>();
        var mailFolderMonitorFactory = scope.ServiceProvider.GetRequiredService<IMailFolderMonitorFactory>();
        async Task UniqueIdArrivedAsync(IMessageSummary messageSummary) =>
            await mailFolderClient.MoveToAsync(messageSummary, destinationFolderFullName, cancellationToken);
        await mailFolderMonitorFactory.MonitorAllMailboxesAsync(UniqueIdArrivedAsync, cancellationToken);
```

**Comment by danzuep** [comment]
Please test the changes and let me know how it goes.

**Comment by Sylar-A** [comment]
Hi, @danzuep!
I cant find the latest pre-release as you mentioned in nuget. There is only previous version.
I've opened it with dotPeek and there aren't your last changes.
Maybe it's GitHub issue, because there is only one rc tag on 2.10.0 too.
![image](https://github.com/danzuep/MailKitSimplified/assets/76655052/2a10bb8b-86a3-4183-9f86-65402521126d)

**Comment by danzuep** [comment]
Ah. it seems that [GitVersion_NuGetVersion] (https://github.com/danzuep/MailKitSimplified/actions/runs/9457376744/job/26051068662) didn't update, even though the semantic version is correct. Weird, that used to work. I re-ran it with a higher version and it [published](https://www.nuget.org/packages/MailKitSimplified.Receiver#versions-body-tab) this time.

**Comment by Sylar-A** [comment]
Hi, @danzuep!
I've found some issues with new code🥲
1. When i try to call `await mailFolderClient.AddFlagsAsync([messageSummary.UniqueId], MessageFlags.Seen);`
it throws an exception:
```
MailKit.Security.AuthenticationException: invalid command
   at MailKit.Net.Imap.ImapClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.ImapReceiver.AuthenticateImapClientAsync(CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.ImapReceiver.ConnectAuthenticatedImapClientAsync(CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.ImapReceiver.ConnectMailFolderAsync(CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderClient.ConnectMailFolderAsync(IMailFolder mailFolder, Boolean enableWrite, CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderClient.ConnectAsync(Boolean enableWrite, CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderClient.AddFlagsAsync(IEnumerable`1 uniqueIds, MessageFlags messageFlags, Boolean silent, CancellationToken cancellationToken)
```
Somewhere here (deeper in MailKit):
![image](https://github.com/danzuep/MailKitSimplified/assets/76655052/86a35b5a-4b78-4df8-890f-6c09a3029da4)

2. When i try to call `await mailFolderClient.MoveToAsync(messageSummary, _archiveFolderName);`
it throws an NullReferenceException with _mailFolderCache because of mailFolder is null:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MailKitSimplified.Receiver.Services.MailFolderCache.CacheMailFolder(IMailFolder mailFolder)
   at MailKitSimplified.Receiver.Services.MailFolderCache.GetMailFolderAsync(IImapReceiver imapReceiver, String mailFolderFullName, CancellationToken cancellationToken)
```
![image](https://github.com/danzuep/MailKitSimplified/assets/76655052/e657bac7-1ef3-4226-af8b-3cd5cfdebc05)

**Comment by danzuep** [comment]
Some of the issues you mentioned are fixed in the latest pre-release, try updating. The main thing I haven't tried is creating folders, but the other ones should work now.

**Comment by Sylar-A** [comment]
Hi, Daniel!
Thank you for fixes!
But I still can't see new rc version in nuget packages🥲
Maybe you'll release a new version after all fixes?

**Comment by danzuep** [comment]
Looks like it was there when you commented, but just in case I've [made a new one](https://www.nuget.org/packages/MailKitSimplified.Sender#versions-body-tab). Please do a Pull Request if you notice any issues.

**Comment by Sylar-A** [comment]
Hi, @danzuep!
Second point of [comment](https://github.com/danzuep/MailKitSimplified/issues/63#issuecomment-2161228006) was fixed, thanks!
But first is still throws and now on both mailFolderClient.AddFlagsAsync() and mailFolderClient.MoveToAsync() methods(
Maybe the problem is in empty ImapCredentials here? It's filled in appsettings.json file.
![image](https://github.com/danzuep/MailKitSimplified/assets/76655052/edd2d423-5eb9-4545-90d8-9d35a67ffc01)

**Comment by danzuep** [comment]
It seems it's a problem with your authentication settings, but the issue isn't clear from the error message (`MailKit.Security.AuthenticationException: invalid command`). What's the ProtocolLog saying?

**Comment by Sylar-A** [comment]
It says
```
Connected to imaps://imap.mail.ru:993/
S: * OK IMAP4 ready
C: V00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 ID XLIST UIDPLUS UNSELECT MOVE LIST-STATUS SASL-IR AUTH=PLAIN AUTH=XOAUTH2
S: V00000000 OK CAPABILITY completed
C: V00000001 AUTHENTICATE PLAIN ********
S: V00000001 NO [AUTHENTICATIONFAILED] NEOBHODIM parol prilozheniya https://help.mail.ru/mail/security/protection/external / Application password is REQUIRED
C: V00000002 LOGIN "" ""
S: V00000002 BAD invalid command
```

**Comment by danzuep** [comment]
"Application password is REQUIRED" (Gmail has the same requirement).
The capability line includes AUTH=XOAUTH2, if you you just want to get it working, you can use `imapReceiver.RemoveAuthenticationMechanism("XOAUTH2");`.

> Authenticating via a SASL mechanism may be a multi-step process.
> see href="http://www.mimekit.net/docs/html/T_MailKit_Security_SaslMechanism.htm"
> seealso href="http://www.mimekit.net/docs/html/T_MailKit_Security_SaslMechanismOAuth2.htm"

**Comment by Sylar-A** [comment]
Hi, @danzuep!
The error is not in XOAUTH2  mechanism, it's in PLAIN.
In this image you can see that credentials are not empty
![image](https://github.com/danzuep/MailKitSimplified/assets/76655052/5827a31d-f7df-4ab5-9986-3abcf498fb38)
In this image it's empty (when i use mailFolderClient mrthods AddFlagsAsync and MoveToAsync)
![image](https://github.com/danzuep/MailKitSimplified/assets/76655052/5c5efa30-7f1f-4665-b91e-545a108fa8a1)

**Comment by Sylar-A** [comment]
Hi @danzuep!
Any decision with this bug?
I suppose the problem is in resolving configs in new instances of services (after register them as scope/transient).
I can't use your new code because of it.
Please, help🙏

**Comment by danzuep** [comment]
I haven't been able to replicate the issue you're having sorry. Have you tried connecting to GMail or one of the other big providers? Try downloading the source code and using breakpoints to pinpoint the issue.

**Comment by danzuep** [comment]
I finally came back to this in a spare evening, it's working now after a few small fixes.

![Image](https://github.com/user-attachments/assets/06e90e79-17c9-432e-a68c-574db3bac889)

![Image](https://github.com/user-attachments/assets/e514febd-646b-4bd7-bdb2-314bd4d413c0)
